### ISSUE TITLE
Is browser platform supported?

### ISSUE THREAD

**Issue by amreladawy** [EddyVerbruggen/cordova-plugin-googleplus#369]
I am building my Ionic 2 app for browser platform. But still getting the following errors.

`exec proxy not found for :: GooglePlus :: login`
`Missing Command Error`

Is browser platform supported?

**Comment by juanjose49** [comment]
+1

**Comment by juanjose49** [comment]
I'm not sure if it's totally related but I'm just going to throw this out there: maybe this error actually represents a problem with the fact that our apps are not running over HTTPS? I just noticed that another plugin I'm using says: "getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS". Maybe it's a similar problem.

Either way, it would be great to get clarification on what is a pretty cryptic error. If this is in fact the problem the error should be updated to reflect the true problem.

**Comment by odiagroup** [comment]
Same error does anybody find a way to fix it ?

**Comment by amreladawy** [comment]
I am using HTTPS.

**Comment by misterjojo** [comment]
I'm facing the same issue, this plugins seems to be incompatible with platform browser. Have you find a workaround to make it work on ios, android and browsers ?

**Comment by habibillah** [comment]
I have make [PR](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/414) for this issue. if you can't wait, just checkout my fork

**Comment by robgungor** [comment]
Same issue, same error.

**Comment by amreladawy** [comment]
As a workaround now, you can add 
```
<script src="https://apis.google.com/js/platform.js"></script>
```

To the index.html

**Comment by mzealey** [comment]
@habibillah good work with the browser plugin. Works ok for normal auth. However there is an issue with the lazy-loading callbacks eg:

```
            return __googleCallbacks.push(function() {
                this.trySilentLogin(success, error, options);
            });
```

You need to use `var self = this` in the outer scope and then use that as the `this` within the callback references the array, alternatively use `.call` while running them after load.

**Comment by mzealey** [comment]
I have fixed the above and another few issues/improvements in https://github.com/mzealey/cordova-plugin-googleplus . This works well in my browser tests now.

**Comment by djejaquino** [comment]
@habibillah @mzealey Hello and good job on the browser implementation and fixes. 
Would any of you show me how to make your custom version work? I tried:

```
$ ionic cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid
$ npm install --save @ionic-native/google-plus
$ npm install --save git+https://git@github.com/mzealey/cordova-plugin-googleplus.git
```
Then, I added the _GOOGLE_PLUS_CLIENT_ID_ config as stated in the README.
I checked _node_modules_ and the installed package is yours. 
But when running browser platform, I still get `exec proxy not found for :: GooglePlus :: login Missing Command Error`

What am I missing? Thanks.

**Comment by habibillah** [comment]
> $ ionic cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid

that command refer to wrong repo. that will get from https://www.npmjs.com/package/cordova.plugin.googleplus

you should use

>  $ ionic cordova plugin add https://github.com/habibillah/cordova-plugin-googleplus.git --variable REVERSED_CLIENT_ID=myreversedclientid

**Comment by djejaquino** [comment]
@habibillah I've tried that before but I get a cordova error, probably related to [this](https://stackoverflow.com/questions/30801307/upgrade-cordova-cannot-install-plugins-from-git-urls-anymore) issue.
What I did and actually **worked** was cloning your fork and installing from local repo, like this:

```
ionic cordova plugin add ../cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid
```

I appreciate your effort on making this improvement available for the community.
